version: '3.8'

services:
  banbot:
    container_name: banbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - /ban:/ban
    environment:
      - BanDataDir=/ban/data
      - BanStratDir=/ban/strats
    restart: unless-stopped
