# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web/ui/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web/ui/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/ui/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: web/ui
    
    - name: Build frontend
      run: npm run build
      working-directory: web/ui
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: web/ui/dist/
        retention-days: 7
        if-no-files-found: error
